import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { StrictMode } from 'react'
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { dismissTopAndroidOverlay } from '../utils/androidBack'
import LiveCamera from './LiveCamera'

const mocks = vi.hoisted(() => ({ native: false, take: vi.fn(), blob: vi.fn(), cancelled: vi.fn() }))
vi.mock('../utils/nativeCamera', () => ({ hasNativeCamera: () => mocks.native, takeNativePhoto: mocks.take, cameraPhotoBlob: mocks.blob, isCameraCancelled: mocks.cancelled }))
const PHOTO = 'data:image/jpeg;base64,U1lOVEhFVElD'
let getUserMedia, track, media, canvasContext, visibility
const deferred = () => { let resolve, reject; const promise = new Promise((yes, no) => { resolve = yes; reject = no }); return { promise, resolve, reject } }
function makeMedia(capabilities = {}, settings = {}) {
  const cameraTrack = { stop: vi.fn(), getCapabilities: vi.fn(() => capabilities), getSettings: vi.fn(() => settings), applyConstraints: vi.fn(async () => {}), addEventListener: vi.fn(), removeEventListener: vi.fn() }
  return { track: cameraTrack, stream: { getTracks: () => [cameraTrack], getVideoTracks: () => [cameraTrack] } }
}
const mount = props => render(<LiveCamera onCapture={vi.fn()} onClose={vi.fn()} {...props} />)
async function loaded(width = 1920, height = 1080) {
  const element = screen.getByLabelText('Live camera preview')
  await waitFor(() => expect(element.srcObject).toBeTruthy())
  Object.defineProperty(element, 'videoWidth', { configurable: true, value: width })
  Object.defineProperty(element, 'videoHeight', { configurable: true, value: height })
  fireEvent.loadedMetadata(element)
  return element
}
beforeEach(() => {
  vi.clearAllMocks()
  mocks.native = false
  mocks.take.mockReset().mockResolvedValue({ webPath: 'https://localhost/_capacitor_file_/synthetic.jpg' })
  mocks.blob.mockReset().mockResolvedValue(new Blob(['synthetic'], { type: 'image/jpeg' }))
  mocks.cancelled.mockReset().mockImplementation(error => error?.code === 'CAMERA_CANCELLED')
  const camera = makeMedia(); track = camera.track; media = camera.stream
  getUserMedia = vi.fn(async () => media)
  Object.defineProperty(navigator, 'mediaDevices', { configurable: true, value: { getUserMedia } })
  visibility = 'visible'
  vi.spyOn(document, 'visibilityState', 'get').mockImplementation(() => visibility)
  vi.spyOn(HTMLMediaElement.prototype, 'play').mockResolvedValue(undefined)
  canvasContext = { drawImage: vi.fn() }
  vi.spyOn(HTMLCanvasElement.prototype, 'getContext').mockReturnValue(canvasContext)
  vi.spyOn(HTMLCanvasElement.prototype, 'toDataURL').mockReturnValue(PHOTO)
  class CameraReader {
    readAsDataURL() { this.result = PHOTO; queueMicrotask(() => this.onload?.()) }
  }
  vi.stubGlobal('FileReader', CameraReader)
})
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals() })

describe('browser live camera review', () => {
  it('requests rear HD video without audio and waits for real metadata dimensions', async () => {
    mount()
    expect(getUserMedia).toHaveBeenCalledWith({ video: { facingMode: { ideal: 'environment' }, width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false })
    const capture = screen.getByRole('button', { name: 'Capture photo' })
    await waitFor(() => expect(HTMLMediaElement.prototype.play).toHaveBeenCalled())
    expect(capture).toBeDisabled()
    await loaded(0, 0)
    expect(capture).toBeDisabled()
    await loaded()
    expect(capture).toBeEnabled()
    expect(screen.queryByRole('slider')).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Turn torch on' })).not.toBeInTheDocument()
  })
  it('stops the stream, captures an unmirrored bounded JPEG and requires Use photo before attachment', async () => {
    const onCapture = vi.fn(async () => {}), onClose = vi.fn()
    track.getSettings.mockReturnValue({ facingMode: 'user' })
    mount({ onCapture, onClose })
    const element = await loaded()
    expect(element).toHaveStyle({ transform: 'scaleX(-1)' })
    fireEvent.click(screen.getByRole('button', { name: 'Capture photo' }))
    expect(track.stop).toHaveBeenCalled()
    expect(screen.getByRole('dialog', { name: 'Review photo' })).toBeInTheDocument()
    expect(screen.getByRole('img', { name: 'Photo ready for review' })).toHaveAttribute('src', PHOTO)
    const [source, x, y, width, height] = canvasContext.drawImage.mock.calls[0]
    expect([source, x, y, width, height]).toEqual([element, 0, 0, 1280, 720])
    expect(HTMLCanvasElement.prototype.toDataURL).toHaveBeenCalledWith('image/jpeg', .75)
    expect(onCapture).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Use photo' }))
    await waitFor(() => expect(onClose).toHaveBeenCalledOnce())
    expect(onCapture).toHaveBeenCalledWith(PHOTO)
  })
  it('keeps review after an attachment failure and prevents close/back/retake while attachment is running', async () => {
    const pending = deferred(), onClose = vi.fn(), onCapture = vi.fn(() => pending.promise)
    mount({ initialPhoto: PHOTO, onCapture, onClose })
    expect(getUserMedia).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Use photo' }))
    expect(screen.getByRole('button', { name: 'Close camera' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Retake' })).toBeDisabled()
    fireEvent.keyDown(document, { key: 'Escape' })
    act(() => expect(dismissTopAndroidOverlay()).toBe(true))
    expect(onClose).not.toHaveBeenCalled()
    await act(async () => { pending.reject(new Error('Synthetic compression failed')); await pending.promise.catch(() => {}) })
    expect(screen.getByRole('alert')).toHaveTextContent('Your preview is still here')
    expect(screen.getByRole('img', { name: 'Photo ready for review' })).toBeVisible()
    expect(screen.getByRole('button', { name: 'Use photo' })).toBeEnabled()
  })
  it('restarts a stopped camera for Retake and never auto-attaches either frame', async () => {
    const onCapture = vi.fn()
    mount({ onCapture })
    await loaded()
    fireEvent.click(screen.getByRole('button', { name: 'Capture photo' }))
    fireEvent.click(screen.getByRole('button', { name: 'Retake' }))
    await waitFor(() => expect(getUserMedia).toHaveBeenCalledTimes(2))
    expect(screen.queryByRole('img', { name: 'Photo ready for review' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Capture photo' })).toBeDisabled()
    expect(onCapture).not.toHaveBeenCalled()
  })
  it('stops the old track before front/rear switching and requires fresh metadata', async () => {
    const second = makeMedia({}, { facingMode: 'user' })
    getUserMedia.mockResolvedValueOnce(media).mockImplementationOnce(async () => { expect(track.stop).toHaveBeenCalled(); return second.stream })
    mount()
    await loaded()
    fireEvent.click(screen.getByRole('button', { name: 'Switch camera' }))
    await waitFor(() => expect(getUserMedia).toHaveBeenCalledTimes(2))
    expect(getUserMedia.mock.calls[1][0].video.facingMode).toEqual({ ideal: 'user' })
    expect(screen.getByRole('button', { name: 'Capture photo' })).toBeDisabled()
    const next = await loaded()
    expect(next).toHaveStyle({ transform: 'scaleX(-1)' })
    expect(screen.getByRole('button', { name: 'Capture photo' })).toBeEnabled()
  })
  it('shows and applies only supported torch and zoom hardware settings', async () => {
    track.getCapabilities.mockReturnValue({ torch: [false, true], zoom: { min: 1, max: 4, step: .5 } })
    mount()
    await loaded()
    fireEvent.click(screen.getByRole('button', { name: 'Turn torch on' }))
    await screen.findByRole('button', { name: 'Turn torch off' })
    expect(track.applyConstraints).toHaveBeenCalledWith({ advanced: [{ torch: true }] })
    fireEvent.change(screen.getByRole('slider', { name: /Zoom/ }), { target: { value: '2' } })
    await waitFor(() => expect(screen.getByText('Zoom: 2.0×')).toBeVisible())
    expect(track.applyConstraints).toHaveBeenLastCalledWith({ advanced: [{ zoom: 2 }] })
  })
  it('omits hardware controls when the track cannot apply constraints', async () => {
    track.getCapabilities.mockReturnValue({ torch: true, zoom: { min: 1, max: 3 } })
    delete track.applyConstraints
    mount()
    await loaded()
    expect(screen.queryByRole('slider')).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Turn torch on' })).not.toBeInTheDocument()
  })
  it.each([
    ['NotAllowedError', 'Camera access was refused'],
    ['NotFoundError', 'No camera was found'],
    ['NotReadableError', 'Close other apps using it'],
  ])('categorizes %s and lets the user explicitly retry', async (name, message) => {
    getUserMedia.mockRejectedValueOnce(Object.assign(new Error('Synthetic camera error'), { name }))
    mount()
    expect(await screen.findByRole('alert')).toHaveTextContent(message)
    fireEvent.click(screen.getByRole('button', { name: 'Retry camera' }))
    await loaded()
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(getUserMedia).toHaveBeenCalledTimes(2)
  })
  it('offers no upload/gallery control if live camera support is absent', async () => {
    Object.defineProperty(navigator, 'mediaDevices', { configurable: true, value: undefined })
    const view = mount()
    expect(await screen.findByRole('alert')).toHaveTextContent('continue your report without a photo')
    expect(view.container.querySelector('input[type="file"]')).toBeNull()
    expect(document.querySelector('input[type="file"]')).toBeNull()
    expect(mocks.take).not.toHaveBeenCalled()
  })
  it('stops late permission results after unmount instead of leaving the camera active', async () => {
    const pending = deferred()
    getUserMedia.mockReturnValue(pending.promise)
    const view = mount()
    view.unmount()
    await act(async () => { pending.resolve(media); await pending.promise })
    expect(track.stop).toHaveBeenCalled()
  })
  it('keeps only the current camera after StrictMode remount and a late first stream', async () => {
    const first = deferred(), old = makeMedia(), current = makeMedia()
    getUserMedia.mockReturnValueOnce(first.promise).mockResolvedValueOnce(current.stream)
    render(<StrictMode><LiveCamera onCapture={vi.fn()} onClose={vi.fn()} /></StrictMode>)
    const element = await loaded()
    expect(element.srcObject).toBe(current.stream)
    await act(async () => { first.resolve(old.stream); await first.promise })
    expect(old.track.stop).toHaveBeenCalled()
    expect(current.track.stop).not.toHaveBeenCalled()
    expect(element.srcObject).toBe(current.stream)
    expect(screen.getByRole('button', { name: 'Capture photo' })).toBeEnabled()
  })
  it('stops live video on background and waits for Resume rather than reopening automatically', async () => {
    mount()
    await loaded()
    visibility = 'hidden'; fireEvent(document, new Event('visibilitychange'))
    expect(track.stop).toHaveBeenCalled()
    expect(screen.getByRole('button', { name: 'Capture photo' })).toBeDisabled()
    visibility = 'visible'; fireEvent(document, new Event('visibilitychange'))
    expect(getUserMedia).toHaveBeenCalledOnce()
    fireEvent.click(screen.getByRole('button', { name: 'Resume camera' }))
    await waitFor(() => expect(getUserMedia).toHaveBeenCalledTimes(2))
  })
  it('stops a pending camera that resolves while hidden', async () => {
    const pending = deferred()
    getUserMedia.mockReturnValue(pending.promise)
    mount()
    visibility = 'hidden'; fireEvent(document, new Event('visibilitychange'))
    await act(async () => { pending.resolve(media); await pending.promise })
    expect(track.stop).toHaveBeenCalled()
    expect(screen.getByRole('button', { name: 'Capture photo' })).toBeDisabled()
  })
  it('focuses the dialog, traps Tab, consumes Android back and restores the trigger on unmount', async () => {
    const user = userEvent.setup(), onClose = vi.fn()
    const trigger = document.createElement('button'); trigger.textContent = 'Synthetic trigger'; document.body.append(trigger); trigger.focus()
    const view = mount({ onClose })
    expect(screen.getByRole('button', { name: 'Close camera' })).toHaveFocus()
    await user.tab({ shift: true })
    expect(screen.getByRole('button', { name: 'Close camera' })).toHaveFocus()
    act(() => expect(dismissTopAndroidOverlay()).toBe(true))
    expect(onClose).toHaveBeenCalledOnce()
    expect(document.body.style.overflow).toBe('hidden')
    view.unmount()
    expect(track.stop).toHaveBeenCalled()
    expect(document.body.style.overflow).not.toBe('hidden')
    expect(trigger).toHaveFocus()
    trigger.remove()
  })
})

describe('explicit native camera capture', () => {
  beforeEach(() => { mocks.native = true })
  const callbacks = () => ({ onBeforeNativeCapture: vi.fn(async () => 'synthetic-session'), onNativeResult: vi.fn(async () => {}) })
  it('launches only on tap, waits for persistence before native capture and before review, never auto-attaches', async () => {
    const before = deferred(), after = deferred(), onCapture = vi.fn(), props = callbacks()
    props.onBeforeNativeCapture.mockReturnValue(before.promise)
    props.onNativeResult.mockReturnValue(after.promise)
    mount({ ...props, onCapture })
    expect(getUserMedia).not.toHaveBeenCalled()
    expect(mocks.take).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Open device camera' }))
    expect(mocks.take).not.toHaveBeenCalled()
    await act(async () => { before.resolve('synthetic-session'); await before.promise })
    await waitFor(() => expect(props.onNativeResult).toHaveBeenCalledWith('synthetic-session', { webPath: 'https://localhost/_capacitor_file_/synthetic.jpg' }))
    expect(screen.queryByRole('button', { name: 'Use photo' })).not.toBeInTheDocument()
    await act(async () => { after.resolve(); await after.promise })
    expect(await screen.findByRole('button', { name: 'Use photo' })).toBeEnabled()
    expect(mocks.blob).toHaveBeenCalledWith({ webPath: 'https://localhost/_capacitor_file_/synthetic.jpg' })
    expect(onCapture).not.toHaveBeenCalled()
    expect(document.querySelector('input[type="file"]')).toBeNull()
  })
  it('blocks native launch if the report draft cannot be safely persisted', async () => {
    const props = callbacks()
    props.onBeforeNativeCapture.mockRejectedValue(new Error('Synthetic draft save failed'))
    mount(props)
    fireEvent.click(screen.getByRole('button', { name: 'Open device camera' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('could not be saved safely')
    expect(mocks.take).not.toHaveBeenCalled()
    expect(props.onNativeResult).not.toHaveBeenCalled()
  })
  it('never launches without both draft/recovery callbacks', async () => {
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Open device camera' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('could not be saved safely')
    expect(mocks.take).not.toHaveBeenCalled()
  })
  it('silently persists cancellation as null, without adding a photo or error', async () => {
    const props = callbacks()
    mocks.take.mockRejectedValue({ code: 'CAMERA_CANCELLED' })
    mount(props)
    fireEvent.click(screen.getByRole('button', { name: 'Open device camera' }))
    await waitFor(() => expect(props.onNativeResult).toHaveBeenCalledWith('synthetic-session', null))
    await screen.findByRole('button', { name: 'Open device camera' })
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Use photo' })).not.toBeInTheDocument()
    expect(mocks.blob).not.toHaveBeenCalled()
  })
  it('does not show a native photo if the result owner/recovery confirmation rejects', async () => {
    const props = callbacks()
    props.onNativeResult.mockRejectedValue(new Error('Synthetic account mismatch'))
    mount(props)
    fireEvent.click(screen.getByRole('button', { name: 'Open device camera' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('could not be saved safely')
    expect(mocks.blob).not.toHaveBeenCalled()
    expect(screen.queryByRole('img')).not.toBeInTheDocument()
  })
  it('uses only explicit live browser fallback and returns Retake to the native launch button', async () => {
    const props = callbacks()
    mount(props)
    fireEvent.click(screen.getByRole('button', { name: 'Open device camera' }))
    await screen.findByRole('button', { name: 'Retake' })
    fireEvent.click(screen.getByRole('button', { name: 'Retake' }))
    expect(screen.getByRole('button', { name: 'Open device camera' })).toBeEnabled()
    expect(mocks.take).toHaveBeenCalledOnce()
    fireEvent.click(screen.getByRole('button', { name: 'Use in-app live camera' }))
    await loaded()
    expect(getUserMedia).toHaveBeenCalledOnce()
    expect(document.querySelector('input[type="file"]')).toBeNull()
  })
  it('keeps recovered initialPhoto review-only and never opens either camera automatically', () => {
    const onCapture = vi.fn()
    mount({ ...callbacks(), initialPhoto: PHOTO, onCapture })
    expect(screen.getByRole('button', { name: 'Use photo' })).toBeEnabled()
    expect(getUserMedia).not.toHaveBeenCalled()
    expect(mocks.take).not.toHaveBeenCalled()
    expect(onCapture).not.toHaveBeenCalled()
  })
  it('persists a native result arriving after unmount without creating an unseen review or attachment', async () => {
    const pending = deferred(), props = callbacks(), onCapture = vi.fn()
    mocks.take.mockReturnValue(pending.promise)
    const view = mount({ ...props, onCapture })
    fireEvent.click(screen.getByRole('button', { name: 'Open device camera' }))
    await waitFor(() => expect(mocks.take).toHaveBeenCalledOnce())
    view.unmount()
    await act(async () => { pending.resolve({ webPath: 'https://localhost/_capacitor_file_/synthetic.jpg' }); await pending.promise })
    expect(props.onNativeResult).toHaveBeenCalledWith('synthetic-session', { webPath: 'https://localhost/_capacitor_file_/synthetic.jpg' })
    expect(mocks.blob).not.toHaveBeenCalled()
    expect(onCapture).not.toHaveBeenCalled()
  })
  it('clears a saved pending session instead of opening native camera if the dialog unmounted while saving', async () => {
    const pending = deferred(), props = callbacks()
    props.onBeforeNativeCapture.mockReturnValue(pending.promise)
    const view = mount(props)
    fireEvent.click(screen.getByRole('button', { name: 'Open device camera' }))
    view.unmount()
    await act(async () => { pending.resolve('synthetic-session'); await pending.promise })
    expect(props.onNativeResult).toHaveBeenCalledWith('synthetic-session', null)
    expect(mocks.take).not.toHaveBeenCalled()
  })
})
