import { randomBytes } from 'node:crypto'
import { access, mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { REPO_DIR } from './server-tools.mjs'

export const SERVER_DIR = resolve(REPO_DIR, 'deploy/laptop')
export const MONGO_VOLUME = 'neighbouraid-laptop_mongo_data'
const secret = () => randomBytes(32).toString('hex')
const exists = (path) => access(path).then(() => true, () => false)

export function validateRuntimeConfig(config) {
  if (config?.version !== 1 || !['jwtSecret', 'rootPassword', 'appPassword'].every((key) => typeof config[key] === 'string' && /^[a-f0-9]{64}$/.test(config[key]))) {
    throw new Error('Runtime secrets are invalid. Restore their private backup; no credentials were changed.')
  }
  return config
}

export function newRuntimeConfig() {
  return { version: 1, jwtSecret: secret(), rootPassword: secret(), appPassword: secret() }
}

export async function ensureRuntimeConfig({ directory = SERVER_DIR, existingData = false } = {}) {
  await mkdir(directory, { recursive: true })
  const source = resolve(directory, 'runtime-secrets.private.json')
  const appFile = resolve(directory, 'app.private.env')
  const mongoFile = resolve(directory, 'mongo.private.env')
  let config
  try {
    config = JSON.parse(await readFile(source, 'utf8'))
  } catch (error) {
    if (error.code !== 'ENOENT') throw new Error('Runtime secrets are invalid. Restore their private backup; do not regenerate database credentials.')
    // Move older installs to private filenames without changing DB passwords.
    // Deliberate password rotation is a separate authenticated operation.
    const legacySource = resolve(directory, 'runtime-secrets.json')
    if (await exists(legacySource)) {
      try { config = validateRuntimeConfig(JSON.parse(await readFile(legacySource, 'utf8'))) } catch {
        throw new Error('Legacy runtime secrets are invalid. Restore their private backup.')
      }
    } else if (existingData || await exists(appFile) || await exists(mongoFile) || await exists(resolve(directory, 'app.env')) || await exists(resolve(directory, 'mongo.env'))) {
      throw new Error('Database configuration is missing but data/configuration already exists. Restore runtime-secrets.private.json from backup; no credentials were changed.')
    } else {
      config = newRuntimeConfig()
    }
    await writeFile(source, `${JSON.stringify(config)}\n`, { flag: 'wx', mode: 0o600 })
  }
  validateRuntimeConfig(config)
  // Rebuild only generated files from the stable master. The API receives
  // neither the root user nor the root password.
  await writeFile(appFile, [
    '# Generated private configuration. Rotate with server:rotate; do not edit passwords by hand.',
    `JWT_SECRET=${config.jwtSecret}`,
    `MONGO_URL=mongodb://neighbouraid_app:${config.appPassword}@mongo:27017/neighbouraid?authSource=neighbouraid`,
    '',
  ].join('\n'), { mode: 0o600 })
  await writeFile(mongoFile, [
    '# Generated by server:setup; initialization applies only to an empty volume.',
    'MONGO_INITDB_ROOT_USERNAME=neighbouraid_admin',
    `MONGO_INITDB_ROOT_PASSWORD=${config.rootPassword}`,
    'MONGO_INITDB_DATABASE=neighbouraid',
    'MONGO_APP_USER=neighbouraid_app',
    `MONGO_APP_PASSWORD=${config.appPassword}`,
    '',
  ].join('\n'), { mode: 0o600 })
}
